# Generated by Django 6.0.1 on 2026-01-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessrolerule',
            unique_together={('role', 'element')},
        ),
    ]
